Word = ['mouse', 'cat', 'dog', 'fox', 'wolf', 'snack', 'monitor', 'water', 'math', 'science', 'immune', 'EpikHigh','data','milk', 'human', 'science', 'math', 'water', 'chocolate', 'lilac', 'summer', 'spring', 'winter', 'fall']
ko_Word = ['닭', '한글', '세종대왕', '코코팜', '부채', '연필', '필통', '과자', '배배', '지우개', '종이', '단짝', '책', '모니터', '선풍기', '에어컨', '가방', '미적분', '수학', '물리학', '재미', '안약', '이어폰']

srt = ['Wealth bring with it many anxieties.', 'There is nothing either good or bad but thinking makes it so.', 'Though she be but little, she is fierce.']
ko_srt = ['덕이 없는 아름다움은 향기 없는 꽃이다.', '나는 완고한 덕보다는 융통성이 있는 악덕을 좋아한다.', '기둥이 약하면 집이 흔들리듯 의지가 약하면 생활도 휘청거린다.', '상황은 사람을 구속하지 않는다. 단지 그 사람의 됨됨이를 드러내줄 뿐이다.']

national_anthem = ['1. 동해물과 백두산이 마르고 닳도록', '하느님이 보우하사 우리나라 만세', '무궁화 삼천리 화려강산', '대한사람 대한으로 길이 보전하세']


#  긴 글의 배열의 0번은 제목, 1번은 내용
counting_star = ['별 헤는 밤', '계절이 지나가는 하늘에는 가을로 가득 차 있습니다. 나는 아무 걱정도 없이 가을 속의 별들을 다 헬 듯합니다. 가슴 속에 하나 둘 새겨지는 별을 이제 다 못 헤는 것은 쉬이 아침이 오는 까닭이요, 내일 밤이 남은 까닭이요, 아직 나의 청춘이 다하지 않은 까닭입니다. 별 하나에 추억과 별 하나에 사랑과 별 하나에 쓸쓸함과 별 하나에 사랑과 별 하나에 어머니, 어머니, 어머님, 나는 별 하나에 아름다운 말 한 마디씩 불러 봅니다. 소학교 때 책상을 같이 했던 아이들의 이름과 패, 경, 옥 이런 이국 소녀들의 이름과 벌써 아기 어머니된 계집애들의 이름과, 가난한 이웃 사람들의 이름과, 비둘기, 강아지, 토끼, 노새, 노루, 프랑시스 잠, 라이너 마리아 릴케 이런 시인의 이름을 불러 봅니다. 이네들은 너무나 멀리 있습니다. 별이 아스라이 멀듯이. 어머님, 그리고 당신은 북간도에 계십니다. 나는 무엇인지 그리워 이 많은 별빛이 내린 언덕 위에 내 이름자를 써보고 흙으로 덮어 버리었읍니다. 딴은 밤을 세워 우는 벌레는 부끄러운 이름을 슬퍼하는 까닭입니다. 그러나, 겨울이 지나고 나의 별에도 봄이 오면, 무덤 위에 파란 잔디가 피어나듯이 내 이름자 묻힌 언덕 위에도 자랑처럼 무성할 거외다.']
gold_axe = ['금도끼', '나무꾼 한 사람이 연못가에서 큰 나무를 베다가 번쩍 든 도끼를 놓쳐서 그 도끼가 연못물 속에 풍덩 들어가 버렸습니다. 한없이 깊은 연못 속에 들어갔으니까 다시 찾을 생각도 못하고 나무꾼은 그냥 연못가에 쓰러져서 탄식을 하고 있노라니까 어여쁜 물귀신이 나와서 무엇 때문에 탄식을 하느냐고 묻습니다. 그래 도끼 잃어버린 말을 하니까, "염려 말게, 내가 찾아다 줌세."하고, 물속으로 들어가더니 한참 만에 번쩍번쩍하는 좋은 금도끼를 가지고 나와서, "네게 이것이냐?"고 물으므로 나무꾼은 정직하게 아니라고 하였습니다. 그러니까 다시 들어가더니 한참 만에 이번에는 좋은 은도끼를 들고 나와서 이것이냐고 물었으므로 또, "그것도 아니올시다."하였습니다. 그러니까 세 번째 또 들어가더니 한참 만에 이번에는 보통 쇠도끼를 가지고 나왔기 때문에 나무꾼은 그제야, "예예, 그것이 제 것이올시다."하였습니다. 그러니까 물귀신은 나무꾼의 마음이 정직한 것을 기특히 여기고, 그 금도끼 은도끼까지 모두 내주었습니다. 마음 정직한 나무꾼이 은도끼 금도끼를 얻어서 수가 난 것을 보고 샘 잘 내는 친구 한 놈이 그 길로 자기 집 도끼를 들고 연못가로 뛰어가서 일부러 도끼를 연못물 속에 던져 넣었습니다. 이번에도 물귀신이 나와서 도끼를 잃어버렸단 말을 듣고 다시 들어가더니, 번쩍번쩍하고 좋은 금도끼를 들고 나와서, "네게 이것이냐?"하였습니다. "예, 그것이 제 것이올시다."하고, 두 손을 내밀었습니다. 그러나 어여쁜 물귀신은 눈을 크게 뜨고, "예끼 못된 놈."하고 금도끼를 주지도 않고 그냥 물속으로 들어가 버렸습니다. 그래서 가지고 갔던 도끼만 잃어버리고 말았습니다.']

narcissus = ['Narcissus', 'Long, Long ago, there lived in Greece a young boy named Narcissus. All day long he tended his sheep in the hills, and drove them from place to place to find the very best pasture. One day he came to a little stream and wanted to drink from it. The water was very clear and reflected everything that leaned over it. While Narcissus was waiting for the sheep to drink, he chanced to see his own face in the water. He had never seen his likeness before, and he was so pleased with the pretty picture that he looked at it for a long time. He forgot all about his sheep. The sheep waited for a long time near stream, but at last they wander-ed away without the shepherd and were lost. Jupiter, the great god of that country, was very angry with Narcissus for forgetting his sheep, and made up his mind to pusnish him. So Narcissus looked at himself very long, and when he turned to look after his flock he found that his feet had taken root. He could not move nor lift his head, but had to keep it hung down. Then, little by little, he changed into the flower that we know so well, the narcissus. This is why we often find this dainty flower growing on the banks of streams and always with its pretty head hung down.']